### ISSUE TITLE
Start: 20/01/2023 | End: 01/02/2023 - Architectural/Component Diagram

### ISSUE THREAD

**Issue by FS75** [FS75/ICT2106_P2-2#4]
The team will create an architectural diagram including the components and interfaces that will be utilised in the system, based on the features that our team is working on

**Comment by personryan** [comment]
20/1/2023: Tentative architectural diagram (to be updated after evaulation in W4)


![Image](https://user-images.githubusercontent.com/90229655/213859506-9d1c82ce-59bb-4296-adb1-a3007dffc8c2.png)

**Comment by FS75** [comment]
24/1/2023: Tentative architectural diagram V2 (to be updated after evaulation in W4)

![Image](https://user-images.githubusercontent.com/93301912/214261125-24c6cc62-eec7-47e3-9a85-ae212e835ca8.png)

**Comment by FS75** [comment]
1/2/2023: Completed Component Diagram


![Image](https://user-images.githubusercontent.com/93301912/216030159-c6bf6294-fbca-490f-bf38-f748beba6820.png)
