### ISSUE TITLE
Start: 20/01/2023 | End: xx/01/2023 - Class Diagram (interfaces only)

### ISSUE THREAD

**Issue by FS75** [FS75/ICT2106_P2-2#5]
The team will create a class diagram including ONLY the interfaces that will be utilised in the system, based on the features that our team is working on

**Comment by personryan** [comment]
20/1/2023: Tentative interfaces with methods (to be updated after evaluation in W4)


![Image](https://user-images.githubusercontent.com/90229655/213859450-f4ee7f62-1f76-427c-9a46-72e5cb6573ab.png)

**Comment by FS75** [comment]
24/1/2023: Tentative interfaces with methods V2 (to be updated after evaluation in W4)

![Image](https://user-images.githubusercontent.com/93301912/214261250-c2ba3520-a642-4637-b95a-a677abe935ae.png)

**Comment by FS75** [comment]
1/2/2023: Completed interface classes

Note: "Completed" refers to the interface classes providing the sufficient methods at the time of posting. In future, more methods might be added into the interfaces as we progress with possible client requirement changes or other teams needing our team to implement more methods.

IAccountService:

![Image](https://user-images.githubusercontent.com/93301912/216029007-eef7df7d-af94-41b1-beac-300e5962a714.png)

IProfileService:

![Image](https://user-images.githubusercontent.com/93301912/216029764-16d6c7f4-77ce-44e0-8c90-5dc699ca593a.png)
